### ISSUE TITLE
PyPI: v3.1.7 missing pyx files

### ISSUE THREAD

**Issue by thejinx0r** [nasa/puma#6]
Hi Everyone,

On PyPI, the source archive is missing some pyx files.
At the very least, it's missing  "python/pumapy/generation/tpms_utils.pyx", which prevents a user from running `pip install pumapy==3.1.7`.

It leads to the error below.
Building from source taken from here on github is fine.

The error from PyPI
```
dragonfly_development) [eric@EndeavourOS ~]$ pip install pumapy==3.1.7
Collecting pumapy==3.1.7
  Using cached pumapy-3.1.7.tar.gz (10.9 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/eric/miniconda3/envs/dragonfly_development/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-74moae3z/pumapy_0c85122a7fab4592a924562ada290ad4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-74moae3z/pumapy_0c85122a7fab4592a924562ada290ad4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-w6ylrrlr
       cwd: /tmp/pip-install-74moae3z/pumapy_0c85122a7fab4592a924562ada290ad4/
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-74moae3z/pumapy_0c85122a7fab4592a924562ada290ad4/setup.py", line 22, in <module>
      extensions = cythonize([
    File "/home/eric/miniconda3/envs/dragonfly_development/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 965, in cythonize
      module_list, module_metadata = create_extension_list(
    File "/home/eric/miniconda3/envs/dragonfly_development/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "/home/eric/miniconda3/envs/dragonfly_development/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
      raise ValueError(error_msg)
  ValueError: 'python/pumapy/generation/tpms_utils.pyx' doesn't match any files
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/98/08/993acdc21b62beaccdf9e162043b4bcaa3cccd2fe09933f68d618afd27bd/pumapy-3.1.7.tar.gz#sha256=369c876955954269d902849e49aa54871509474a755745c2719e63e797046884 (from https://pypi.org/simple/pumapy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pumapy==3.1.7 (from versions: 3.1.0.post2, 3.1.0.post3, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7)
ERROR: No matching distribution found for pumapy==3.1.7

```

**Comment by fsemerar** [comment]
Hi Eric, I have actually attempted this on both Mac and Windows but I cannot replicate the error. I used the commands: 
```
conda create --name pip_puma python pip vtk
conda activate pip_puma
pip install pumapy==3.1.7
```
It looks to me as if it was having trouble finding the relative path that is provided in pumapy's setup.py. 
As a side note, I was also having trouble using "pip install pumapy" because of the vtk package, which doesn't seem to be distributed through PyPI for the latest python version. This is why I used conda to install the vtk package directly in the environment.
